# Generated by Django 3.0.5 on 2020-07-29 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='min_vwork',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='chore',
            name='next_date',
            field=models.DateField(default=datetime.date(2020, 7, 30)),
        ),
    ]
