# Generated by Django 3.0.5 on 2020-08-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200809_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
