# Generated by Django 3.0.5 on 2020-08-10 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200809_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='next_date',
            field=models.DateField(default=datetime.date(2020, 8, 11)),
        ),
    ]
